tempo:
  server:
    extraArgs:
      - --search.enabled=true

  traces:
    otlp:
      enabled: true
      http:
        enabled: true

  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi

  persistence:
    enabled: false
