grafana:
  enabled: true
  service:
    type: LoadBalancer
    port: 3000
  adminPassword: "admin"
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: 'custom'
          orgId: 1
          folder: ''
          type: file
          options:
            path: /var/lib/grafana/dashboards/custom

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false

alertmanager:
  enabled: true

nodeExporter:
  enabled: true

kubeStateMetrics:
  enabled: true

tempo:
  traces:
    otlp:
      enabled: true
      http:
        enabled: true
  persistence:
    enabled: true
    storageClassName: gp3
    size: 8Gi

otelcol:
  enabled: true
  name: otelcol
  image: otel/opentelemetry-collector:0.101.0
  configmap: otelcol-config
  lokiEndpoint: http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push