grafana:
  enabled: true
  service:
    type: LoadBalancer
    port: 3000
  adminPassword: "admin"
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: 'custom'
          orgId: 1
          folder: ''
          type: file
          options:
            path: /var/lib/grafana/dashboards/custom

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false

alertmanager:
  enabled: true

nodeExporter:
  enabled: true

kubeStateMetrics:
  enabled: true

tempo:
  server:
    extraArgs:
      - --search.enabled=true
  traces:
    otlp:
      enabled: true
      http:
        enabled: true
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  persistence:
    enabled: false

otelcol:
  enabled: true
  name: otelcol
  image: otel/opentelemetry-collector:0.101.0
  configmap: otelcol-config
  lokiEndpoint: http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push