grafana:
  enabled: true
  service:
    type: LoadBalancer
    port: 3000
  adminPassword: "admin"

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false

alertmanager:
  enabled: true

nodeExporter:
  enabled: true

kubeStateMetrics:
  enabled: true