---
apiVersion: v1
kind: ConfigMap
metadata:
  name: otelcol-config
  namespace: monitoring
data:
  config.yaml: |
    receivers:
      k8slogs:
        include:
          namespaces: ["grpc-app"]
        operators:
          - type: move
            from: attributes.k8s.pod.name
            to: resource.pod.name

    exporters:
      loki:
        endpoint: http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push

    service:
      pipelines:
        logs:
          receivers: [k8slogs]
          exporters: [loki]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otelcol
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otelcol
  template:
    metadata:
      labels:
        app: otelcol
    spec:
      containers:
        - name: otelcol
          image: otel/opentelemetry-collector:0.101.0
          args: ["--config=/etc/otelcol/config.yaml"]
          volumeMounts:
            - name: config-volume
              mountPath: /etc/otelcol
      volumes:
        - name: config-volume
          configMap:
            name: otelcol-config
---
apiVersion: v1
kind: Service
metadata:
  name: otelcol
  namespace: monitoring
spec:
  selector:
    app: otelcol
  ports:
    - name: otlp-http
      port: 4318
      targetPort: 4318