apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.otelcol.name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Values.otelcol.name }}
  ports:
    - name: otlp-http
      port: 4318
      targetPort: 4318
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
  type: ClusterIP